#!/bin/bash

# Check if user 'trape' exits
USER=trape
USEREXISTS=$(id -u $USER >/dev/null 2>&1; echo $?)
EC=0
BASEPATH=/opt/trape
INSTALLPATH=$BASEPATH/collector

# If user does not exist, create it
if (( $USEREXISTS == 1 )); then
	useradd -d $BASEPATH -m -r trape
	EC=$(echo $?)

	if (( $EC == 1 )); then
		exit 1;
	fi
fi

# Set permissions on files
chown -R trape:trape $INSTALLPATH

# Check if config does not exist and create it
if [ ! -f "$INSTALLPATH/settings.json" ]; then
    cp $INSTALLPATH/settings.template.json $INSTALLPATH/settings.json
fi

chmod 644 /etc/systemd/system/trape-collector.service

# Create handy link
ln -s $INSTALLPATH/Trape.Cli.Collector $INSTALLPATH/service

# Create logging dir
mkdir -p /var/log/trape
chown trape:trape /var/log/trape

# Reload systemd because of new trape-collector.service file
systemctl daemon-reload
