// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trape.datalayer;

namespace trape.datalayer.Migrations
{
    [DbContext(typeof(TrapeContext))]
    [Migration("20200507114354_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("trape.datalayer.Models.AccountInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BuyerCommission")
                        .HasColumnName("buyer_commission")
                        .HasColumnType("numeric");

                    b.Property<bool>("CanDeposit")
                        .HasColumnName("can_deposit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTrade")
                        .HasColumnName("can_trade")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWithdraw")
                        .HasColumnName("can_withdraw")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MakerCommission")
                        .HasColumnName("maker_commission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SellerCommission")
                        .HasColumnName("seller_commission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerCommission")
                        .HasColumnName("taker_commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updated_on")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("account_info");
                });

            modelBuilder.Entity("trape.datalayer.Models.Balance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AccountInfoId")
                        .HasColumnName("account_info_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Asset")
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Free")
                        .HasColumnName("free")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Locked")
                        .HasColumnName("locked")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("Id");

                    b.ToTable("balance");
                });

            modelBuilder.Entity("trape.datalayer.Models.BalanceUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Asset")
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<decimal>("BalanceDelta")
                        .HasColumnName("balance_delta")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ClearTime")
                        .HasColumnName("clear_time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("balance_update");
                });

            modelBuilder.Entity("trape.datalayer.Models.BookTick", b =>
                {
                    b.Property<long>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("update_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BestAskPrice")
                        .HasColumnName("best_ask_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestAskQuantity")
                        .HasColumnName("best_ask_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidPrice")
                        .HasColumnName("best_bid_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidQuantity")
                        .HasColumnName("best_bid_quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.HasKey("UpdateId");

                    b.HasIndex("UpdateId");

                    b.HasIndex("CreatedOn", "Symbol");

                    b.ToTable("book_tick");
                });

            modelBuilder.Entity("trape.datalayer.Models.Kline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Close")
                        .HasColumnName("close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnName("close_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Final")
                        .HasColumnName("final")
                        .HasColumnType("boolean");

                    b.Property<long>("FirstTrade")
                        .HasColumnName("first_trade")
                        .HasColumnType("bigint");

                    b.Property<decimal>("High")
                        .HasColumnName("high")
                        .HasColumnType("numeric");

                    b.Property<int>("Interval")
                        .HasColumnName("interval")
                        .HasColumnType("integer");

                    b.Property<long>("LastTrade")
                        .HasColumnName("last_trade")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Low")
                        .HasColumnName("low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnName("open")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnName("open_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasColumnName("quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseAssetVolume")
                        .HasColumnName("taker_buy_base_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteAssetVolume")
                        .HasColumnName("taker_buy_quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<int>("TradeCount")
                        .HasColumnName("trade_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnName("volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OpenTime", "Interval", "Symbol");

                    b.ToTable("kline");
                });

            modelBuilder.Entity("trape.datalayer.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientOrderId")
                        .HasColumnName("client_order_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderListId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ContingencyType")
                        .HasColumnName("contingency_type")
                        .HasColumnType("text");

                    b.Property<string>("ListClientOrderId")
                        .HasColumnName("list_client_order_id")
                        .HasColumnType("text");

                    b.Property<int>("ListOrderStatus")
                        .HasColumnName("list_order_status")
                        .HasColumnType("integer");

                    b.Property<int>("ListStatusType")
                        .HasColumnName("list_status_type")
                        .HasColumnType("integer");

                    b.Property<long>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnName("transaction_time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderListId");

                    b.HasIndex("Symbol");

                    b.ToTable("order_list");
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("AccumulatedQuantityOfFilledTrades")
                        .HasColumnName("accumulated_quantity_of_filled_trades")
                        .HasColumnType("numeric");

                    b.Property<bool>("BuyerIsMaker")
                        .HasColumnName("buyer_is_maker")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientOrderId")
                        .HasColumnName("client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("Commission")
                        .HasColumnName("commission")
                        .HasColumnType("numeric");

                    b.Property<string>("CommissionAsset")
                        .HasColumnName("commission_asset")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CummulativeQuoteQuantity")
                        .HasColumnName("cummulative_quote_quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("ExecutionType")
                        .HasColumnName("execution_type")
                        .HasColumnType("integer");

                    b.Property<long>("I")
                        .HasColumnName("i")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IcebergQuantity")
                        .HasColumnName("iceberg_quantity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsWorking")
                        .HasColumnName("is_working")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastQuoteTransactedQuantity")
                        .HasColumnName("last_quote_transacted_quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OrderCreationTime")
                        .HasColumnName("order_creation_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalClientOrderId")
                        .HasColumnName("original_client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceLastFilledTrade")
                        .HasColumnName("price_last_filled_trade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityOfLastFilledTrade")
                        .HasColumnName("quantity_of_last_filled_trade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuoteOrderQuantity")
                        .HasColumnName("quote_order_quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RejectReason")
                        .HasColumnName("reject_reason")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnName("side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopPrice")
                        .HasColumnName("stop_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<int>("TimeInForce")
                        .HasColumnName("time_in_force")
                        .HasColumnType("integer");

                    b.Property<long>("TradeId")
                        .HasColumnName("trade_id")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderListId");

                    b.HasIndex("OriginalClientOrderId");

                    b.HasIndex("Symbol", "Side");

                    b.ToTable("order_update");
                });

            modelBuilder.Entity("trape.datalayer.Models.Symbol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsCollectionActive")
                        .HasColumnName("is_collection_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradingActive")
                        .HasColumnName("is_trading_active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("symbol");
                });

            modelBuilder.Entity("trape.datalayer.Models.Tick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BestAskPrice")
                        .HasColumnName("best_ask_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestAskQuantity")
                        .HasColumnName("best_ask_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidPrice")
                        .HasColumnName("best_bid_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidQuantity")
                        .HasColumnName("best_bid_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CloseTradesQuantity")
                        .HasColumnName("close_trades_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentDayClosePrice")
                        .HasColumnName("current_day_close_price")
                        .HasColumnType("numeric");

                    b.Property<long>("FirstTradeId")
                        .HasColumnName("first_trade_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("HighPrice")
                        .HasColumnName("high_price")
                        .HasColumnType("numeric");

                    b.Property<long>("LastTradeId")
                        .HasColumnName("last_trade_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LowPrice")
                        .HasColumnName("low_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnName("open_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrevDayClosePrice")
                        .HasColumnName("prev_day_close_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChange")
                        .HasColumnName("price_change")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnName("price_change_percentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StatisticsCloseTime")
                        .HasColumnName("statistics_close_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StatisticsOpenTime")
                        .HasColumnName("statistics_open_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalTradedBaseAssetVolume")
                        .HasColumnName("total_traded_base_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTradedQuoteAssetVolume")
                        .HasColumnName("total_traded_quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<long>("TotalTrades")
                        .HasColumnName("total_trades")
                        .HasColumnType("bigint");

                    b.Property<decimal>("WeightedAverage")
                        .HasColumnName("weighted_average")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("StatisticsOpenTime", "StatisticsCloseTime");

                    b.ToTable("tick");
                });

            modelBuilder.Entity("trape.datalayer.Models.Balance", b =>
                {
                    b.HasOne("trape.datalayer.Models.AccountInfo", "AccountInfo")
                        .WithMany("Balances")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trape.datalayer.Models.Order", b =>
                {
                    b.HasOne("trape.datalayer.Models.OrderList", "OrderList")
                        .WithMany("Orders")
                        .HasForeignKey("OrderListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderUpdate", b =>
                {
                    b.HasOne("trape.datalayer.Models.Order", "Order")
                        .WithMany("OrderUpdates")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trape.datalayer.Models.OrderList", "OrderList")
                        .WithMany("OrderUpdates")
                        .HasForeignKey("OrderListId");
                });
#pragma warning restore 612, 618
        }
    }
}
