// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trape.datalayer;

namespace trape.datalayer.Migrations
{
    [DbContext(typeof(TrapeContext))]
    [Migration("20200720073150_Reference")]
    partial class Reference
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("trape.datalayer.Models.AccountInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BuyerCommission")
                        .HasColumnName("buyer_commission")
                        .HasColumnType("numeric");

                    b.Property<bool>("CanDeposit")
                        .HasColumnName("can_deposit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTrade")
                        .HasColumnName("can_trade")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWithdraw")
                        .HasColumnName("can_withdraw")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MakerCommission")
                        .HasColumnName("maker_commission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SellerCommission")
                        .HasColumnName("seller_commission")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerCommission")
                        .HasColumnName("taker_commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("updated_on")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("account_infos");
                });

            modelBuilder.Entity("trape.datalayer.Models.Balance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AccountInfoId")
                        .HasColumnName("account_info_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Asset")
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Free")
                        .HasColumnName("free")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Locked")
                        .HasColumnName("locked")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnName("total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("Id");

                    b.ToTable("balances");
                });

            modelBuilder.Entity("trape.datalayer.Models.BalanceUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Asset")
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<decimal>("BalanceDelta")
                        .HasColumnName("balance_delta")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ClearTime")
                        .HasColumnName("clear_time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("balance_updates");
                });

            modelBuilder.Entity("trape.datalayer.Models.BookTick", b =>
                {
                    b.Property<long>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("update_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BestAskPrice")
                        .HasColumnName("best_ask_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestAskQuantity")
                        .HasColumnName("best_ask_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidPrice")
                        .HasColumnName("best_bid_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidQuantity")
                        .HasColumnName("best_bid_quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.HasKey("UpdateId");

                    b.HasIndex("UpdateId");

                    b.HasIndex("CreatedOn", "Symbol");

                    b.ToTable("book_ticks");
                });

            modelBuilder.Entity("trape.datalayer.Models.ClientOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("OrderResponseType")
                        .HasColumnName("order_response_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnName("side")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<int?>("TimeInForce")
                        .HasColumnName("time_in_force")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("client_order");
                });

            modelBuilder.Entity("trape.datalayer.Models.Kline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Close")
                        .HasColumnName("close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnName("close_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Final")
                        .HasColumnName("final")
                        .HasColumnType("boolean");

                    b.Property<long>("FirstTrade")
                        .HasColumnName("first_trade")
                        .HasColumnType("bigint");

                    b.Property<decimal>("High")
                        .HasColumnName("high")
                        .HasColumnType("numeric");

                    b.Property<int>("Interval")
                        .HasColumnName("interval")
                        .HasColumnType("integer");

                    b.Property<long>("LastTrade")
                        .HasColumnName("last_trade")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Low")
                        .HasColumnName("low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnName("open")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnName("open_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("QuoteAssetVolume")
                        .HasColumnName("quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("TakerBuyBaseAssetVolume")
                        .HasColumnName("taker_buy_base_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakerBuyQuoteAssetVolume")
                        .HasColumnName("taker_buy_quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<int>("TradeCount")
                        .HasColumnName("trade_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnName("volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OpenTime", "Interval", "Symbol");

                    b.ToTable("klines");
                });

            modelBuilder.Entity("trape.datalayer.Models.LastDecision", b =>
                {
                    b.Property<int>("Action")
                        .HasColumnName("r_action")
                        .HasColumnType("int4");

                    b.Property<DateTime>("EventTime")
                        .HasColumnName("r_event_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("last_decisions","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.LatestMA10mAndMA30mCrossing", b =>
                {
                    b.ToTable("latest_ma10m_and_ma30m_crossing","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.LatestMA1hAndMA3hCrossing", b =>
                {
                    b.ToTable("latest_ma1h_and_ma3h_crossing","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.LatestMA30mAndMA1hCrossing", b =>
                {
                    b.ToTable("latest_ma30m_and_ma1h_crossing","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientOrderId")
                        .HasColumnName("client_order_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderListId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ContingencyType")
                        .HasColumnName("contingency_type")
                        .HasColumnType("text");

                    b.Property<string>("ListClientOrderId")
                        .HasColumnName("list_client_order_id")
                        .HasColumnType("text");

                    b.Property<int>("ListOrderStatus")
                        .HasColumnName("list_order_status")
                        .HasColumnType("integer");

                    b.Property<int>("ListStatusType")
                        .HasColumnName("list_status_type")
                        .HasColumnType("integer");

                    b.Property<long>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnName("transaction_time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderListId");

                    b.HasIndex("Symbol");

                    b.ToTable("order_lists");
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderTrade", b =>
                {
                    b.Property<long>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trade_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Commission")
                        .HasColumnName("commission")
                        .HasColumnType("numeric");

                    b.Property<string>("CommissionAsset")
                        .HasColumnName("commission_asset")
                        .HasColumnType("text");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasColumnName("consumed_quantity")
                        .HasColumnType("numeric");

                    b.Property<long>("PlacedOrderId")
                        .HasColumnName("placed_order_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("numeric");

                    b.HasKey("TradeId");

                    b.HasIndex("PlacedOrderId");

                    b.HasIndex("TradeId");

                    b.ToTable("order_trades");
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("AccumulatedQuantityOfFilledTrades")
                        .HasColumnName("accumulated_quantity_of_filled_trades")
                        .HasColumnType("numeric");

                    b.Property<bool>("BuyerIsMaker")
                        .HasColumnName("buyer_is_maker")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientOrderId")
                        .HasColumnName("client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("Commission")
                        .HasColumnName("commission")
                        .HasColumnType("numeric");

                    b.Property<string>("CommissionAsset")
                        .HasColumnName("commission_asset")
                        .HasColumnType("text");

                    b.Property<decimal>("CummulativeQuoteQuantity")
                        .HasColumnName("cummulative_quote_quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("ExecutionType")
                        .HasColumnName("execution_type")
                        .HasColumnType("integer");

                    b.Property<long>("I")
                        .HasColumnName("i")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IcebergQuantity")
                        .HasColumnName("iceberg_quantity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsWorking")
                        .HasColumnName("is_working")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastQuoteTransactedQuantity")
                        .HasColumnName("last_quote_transacted_quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OrderCreationTime")
                        .HasColumnName("order_creation_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalClientOrderId")
                        .HasColumnName("original_client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceLastFilledTrade")
                        .HasColumnName("price_last_filled_trade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityOfLastFilledTrade")
                        .HasColumnName("quantity_of_last_filled_trade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuoteOrderQuantity")
                        .HasColumnName("quote_order_quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RejectReason")
                        .HasColumnName("reject_reason")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnName("side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopPrice")
                        .HasColumnName("stop_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<int>("TimeInForce")
                        .HasColumnName("time_in_force")
                        .HasColumnType("integer");

                    b.Property<long>("TradeId")
                        .HasColumnName("trade_id")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderListId");

                    b.HasIndex("OriginalClientOrderId");

                    b.HasIndex("Symbol", "Side");

                    b.ToTable("order_updates");
                });

            modelBuilder.Entity("trape.datalayer.Models.PlacedOrder", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("order_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientOrderId")
                        .HasColumnName("client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("CummulativeQuoteQuantity")
                        .HasColumnName("cummulative_quote_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExecutedQuantity")
                        .HasColumnName("executed_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarginBuyBorrowAmount")
                        .HasColumnName("margin_buy_borrow_amount")
                        .HasColumnType("numeric");

                    b.Property<string>("MarginBuyBorrowAsset")
                        .HasColumnName("margin_buy_borrow_asset")
                        .HasColumnType("text");

                    b.Property<long?>("OrderListId")
                        .HasColumnName("order_list_id")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalClientOrderId")
                        .HasColumnName("original_client_order_id")
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnName("original_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OriginalQuoteOrderQuantity")
                        .HasColumnName("original_quote_order_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnName("side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnName("stop_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<int>("TimeInForce")
                        .HasColumnName("time_in_force")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnName("transaction_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderListId");

                    b.HasIndex("OriginalClientOrderId");

                    b.HasIndex("TransactionTime", "Symbol");

                    b.ToTable("placed_orders");
                });

            modelBuilder.Entity("trape.datalayer.Models.Recommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Action")
                        .HasColumnName("action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MovingAverage10m")
                        .HasColumnName("moving_average10m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage10s")
                        .HasColumnName("moving_average10s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage12h")
                        .HasColumnName("moving_average12h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage15m")
                        .HasColumnName("moving_average15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage15s")
                        .HasColumnName("moving_average15s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage18h")
                        .HasColumnName("moving_average18h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage1d")
                        .HasColumnName("moving_average1d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage1h")
                        .HasColumnName("moving_average1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage1m")
                        .HasColumnName("moving_average1m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage2h")
                        .HasColumnName("moving_average2h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage2m")
                        .HasColumnName("moving_average2m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage30m")
                        .HasColumnName("moving_average30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage30s")
                        .HasColumnName("moving_average30s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage3h")
                        .HasColumnName("moving_average3h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage3m")
                        .HasColumnName("moving_average3m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage45s")
                        .HasColumnName("moving_average45s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage5m")
                        .HasColumnName("moving_average5m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage5s")
                        .HasColumnName("moving_average5s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage6h")
                        .HasColumnName("moving_average6h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage7m")
                        .HasColumnName("moving_average7m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope10m")
                        .HasColumnName("slope10m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope10s")
                        .HasColumnName("slope10s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope12h")
                        .HasColumnName("slope12h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope15m")
                        .HasColumnName("slope15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope15s")
                        .HasColumnName("slope15s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope18h")
                        .HasColumnName("slope18h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1d")
                        .HasColumnName("slope1d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1h")
                        .HasColumnName("slope1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1m")
                        .HasColumnName("slope1m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope2h")
                        .HasColumnName("slope2h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope2m")
                        .HasColumnName("slope2m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope30m")
                        .HasColumnName("slope30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope30s")
                        .HasColumnName("slope30s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope3h")
                        .HasColumnName("slope3h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope3m")
                        .HasColumnName("slope3m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope45s")
                        .HasColumnName("slope45s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope5m")
                        .HasColumnName("slope5m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope5s")
                        .HasColumnName("slope5s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope6h")
                        .HasColumnName("slope6h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope7m")
                        .HasColumnName("slope7m")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("CreatedOn", "Symbol");

                    b.ToTable("recommendations");
                });

            modelBuilder.Entity("trape.datalayer.Models.Stats10m", b =>
                {
                    b.Property<int>("DataBasis")
                        .HasColumnName("r_databasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("MovingAverage1h")
                        .HasColumnName("r_movav_1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage2h")
                        .HasColumnName("r_movav_2h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage30m")
                        .HasColumnName("r_movav_30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage3h")
                        .HasColumnName("r_movav_3h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1h")
                        .HasColumnName("r_slope_1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope2h")
                        .HasColumnName("r_slope_2h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope30m")
                        .HasColumnName("r_slope_30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope3h")
                        .HasColumnName("r_slope_3h")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("stats10m","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Stats15s", b =>
                {
                    b.Property<int>("DataBasis")
                        .HasColumnName("r_databasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("MovingAverage1m")
                        .HasColumnName("r_movav_1m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage2m")
                        .HasColumnName("r_movav_2m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage3m")
                        .HasColumnName("r_movav_3m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage45s")
                        .HasColumnName("r_movav_45s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1m")
                        .HasColumnName("r_slope_1m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope2m")
                        .HasColumnName("r_slope_2m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope3m")
                        .HasColumnName("r_slope_3m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope45s")
                        .HasColumnName("r_slope_45s")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("stats15s","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Stats2h", b =>
                {
                    b.Property<int>("DataBasis")
                        .HasColumnName("r_databasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("MovingAverage12h")
                        .HasColumnName("r_movav_12h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage18h")
                        .HasColumnName("r_movav_18h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage1d")
                        .HasColumnName("r_movav_1d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage6h")
                        .HasColumnName("r_movav_6h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope12h")
                        .HasColumnName("r_slope_12h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope18h")
                        .HasColumnName("r_slope_18h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope1d")
                        .HasColumnName("r_slope_1d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope6h")
                        .HasColumnName("r_slope_6h")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("stats2h","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Stats2m", b =>
                {
                    b.Property<int>("DataBasis")
                        .HasColumnName("r_databasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("MovingAverage10m")
                        .HasColumnName("r_movav_10m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage15m")
                        .HasColumnName("r_movav_15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage5m")
                        .HasColumnName("r_movav_5m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage7m")
                        .HasColumnName("r_movav_7m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope10m")
                        .HasColumnName("r_slope_10m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope15m")
                        .HasColumnName("r_slope_15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope5m")
                        .HasColumnName("r_slope_5m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope7m")
                        .HasColumnName("r_slope_7m")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("stats2m","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Stats3s", b =>
                {
                    b.Property<int>("DataBasis")
                        .HasColumnName("r_databasis")
                        .HasColumnType("integer");

                    b.Property<decimal>("MovingAverage10s")
                        .HasColumnName("r_movav_10s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage15s")
                        .HasColumnName("r_movav_15s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage30s")
                        .HasColumnName("r_movav_30s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MovingAverage5s")
                        .HasColumnName("r_movav_5s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope10s")
                        .HasColumnName("r_slope_10s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope15s")
                        .HasColumnName("r_slope_15s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope30s")
                        .HasColumnName("r_slope_30s")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slope5s")
                        .HasColumnName("r_slope_5s")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnName("r_symbol")
                        .HasColumnType("text");

                    b.ToTable("stats3s","stubs");
                });

            modelBuilder.Entity("trape.datalayer.Models.Symbol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsCollectionActive")
                        .HasColumnName("is_collection_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradingActive")
                        .HasColumnName("is_trading_active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("symbols");
                });

            modelBuilder.Entity("trape.datalayer.Models.Tick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("BestAskPrice")
                        .HasColumnName("best_ask_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestAskQuantity")
                        .HasColumnName("best_ask_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidPrice")
                        .HasColumnName("best_bid_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BestBidQuantity")
                        .HasColumnName("best_bid_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CloseTradesQuantity")
                        .HasColumnName("close_trades_quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentDayClosePrice")
                        .HasColumnName("current_day_close_price")
                        .HasColumnType("numeric");

                    b.Property<long>("FirstTradeId")
                        .HasColumnName("first_trade_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("HighPrice")
                        .HasColumnName("high_price")
                        .HasColumnType("numeric");

                    b.Property<long>("LastTradeId")
                        .HasColumnName("last_trade_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LowPrice")
                        .HasColumnName("low_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnName("open_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrevDayClosePrice")
                        .HasColumnName("prev_day_close_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChange")
                        .HasColumnName("price_change")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnName("price_change_percentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StatisticsCloseTime")
                        .HasColumnName("statistics_close_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StatisticsOpenTime")
                        .HasColumnName("statistics_open_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .HasColumnName("symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalTradedBaseAssetVolume")
                        .HasColumnName("total_traded_base_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTradedQuoteAssetVolume")
                        .HasColumnName("total_traded_quote_asset_volume")
                        .HasColumnType("numeric");

                    b.Property<long>("TotalTrades")
                        .HasColumnName("total_trades")
                        .HasColumnType("bigint");

                    b.Property<decimal>("WeightedAverage")
                        .HasColumnName("weighted_average")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("StatisticsOpenTime", "StatisticsCloseTime");

                    b.ToTable("ticks");
                });

            modelBuilder.Entity("trape.datalayer.Models.Balance", b =>
                {
                    b.HasOne("trape.datalayer.Models.AccountInfo", "AccountInfo")
                        .WithMany("Balances")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trape.datalayer.Models.Order", b =>
                {
                    b.HasOne("trape.datalayer.Models.ClientOrder", "ClientOrder")
                        .WithOne("Order")
                        .HasForeignKey("trape.datalayer.Models.Order", "ClientOrderId");

                    b.HasOne("trape.datalayer.Models.OrderList", "OrderList")
                        .WithMany("Orders")
                        .HasForeignKey("OrderListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderTrade", b =>
                {
                    b.HasOne("trape.datalayer.Models.PlacedOrder", "PlacedOrder")
                        .WithMany("Fills")
                        .HasForeignKey("PlacedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trape.datalayer.Models.OrderUpdate", b =>
                {
                    b.HasOne("trape.datalayer.Models.Order", "Order")
                        .WithMany("OrderUpdates")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trape.datalayer.Models.OrderList", "OrderList")
                        .WithMany("OrderUpdates")
                        .HasForeignKey("OrderListId");
                });
#pragma warning restore 612, 618
        }
    }
}
